---
- hosts: all
  remote_user: root
  tasks:

    - name: "Install needed software"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ipython
        - inkscape

    - name: "Set passwords"
      user:
        name: "{{ item }}"
        password: "$6$L75UYqwVvEyRWX08$mZpBH3DMVIcUi2D5xaYgFClHw0iPVup.wwO8H.vnnp2pIp1LcgFpqv4B3KmWes40XdANatbGguTu3ZVKRs85V."
        update_password: always
      with_items:
        - root
        - pi

    - name: "Clone RaspberryJam repository"
      git:
        repo: 'https://github.com/magictimelapse/RaspberryJamSchweiz.git'
        dest: /home/pi/RaspberryJamSchweiz
      become: yes
      become_user: pi

    - name: "Remove Games"
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - minecraft-pi
        - python3-pygame